game:
	g++ -c main.cpp player.cpp bullet.cpp enemy.cpp enemybullet.cpp
	g++ main.o player.o bullet.o enemy.o enemybullet.o -o game -lsfml-graphics -lsfml-window -lsfml-system

clean:
	rm -r *.o
	rm -r game
